### ISSUE TITLE
fgplvm demOil4 error

### ISSUE THREAD

**Issue by junjun16** [SheffieldML/GPmat#12] opened 2016-06-11 23:31 UTC
I ran the demo demOil4. 
The errors went from positive to negative and continue to decrease, like following.
Cycle   13  Error 20962.592172  Scale 2.083569e+04
Cycle   14  Error 12966.345081  Scale 1.041785e+04
Cycle   15  Error 5170.066683  Scale 5.208923e+03
Cycle   16  Error 2142.240905  Scale 2.604461e+03
Cycle   17  Error -1369.209243  Scale 1.302231e+03
Cycle   18  Error -2120.706700  Scale 6.511154e+02
Cycle   19  Error -3046.368921  Scale 3.255577e+02
Cycle   20  Error -3528.695085  Scale 1.627788e+02
Cycle   21  Error -3834.332228  Scale 8.138942e+01
Cycle   22  Error -4124.404594  Scale 4.069471e+01
Cycle   23  Error -4296.765671  Scale 2.034735e+01

It seems to go unbounded and won't stop.

**Comment by lawrennd** [comment] 2016-06-12 06:02
That's the expected behaviour, you are seeking the objective function
minimise, seems all is working.

**Comment by adamian** [comment] 2018-01-09 23:34
Seems we can close this. Just a quick addition, the negative error (value of the objective) is because we actually compute the logarithm of the objective, which can be negative.

**Closed by adamian** 2018-01-09 23:34 UTC
